USE GD1C2020;

--====Dropeos====--

DROP TABLE EQUIPO_RAYO.Clientes
DROP TABLE EQUIPO_RAYO.Empresas
DROP TABLE EQUIPO_RAYO.Aviones 
DROP TABLE EQUIPO_RAYO.Butacas 
DROP TABLE EQUIPO_RAYO.Rutas 
DROP TABLE EQUIPO_RAYO.Compras 
DROP TABLE EQUIPO_RAYO.Sucursales
DROP TABLE EQUIPO_RAYO.Tipos
DROP TABLE EQUIPO_RAYO.Vuelos 
DROP TABLE EQUIPO_RAYO.Hoteles
DROP TABLE EQUIPO_RAYO.Habitaciones
DROP TABLE EQUIPO_RAYO.Estadias_Habitaciones
DROP TABLE EQUIPO_RAYO.Estadias
DROP TABLE EQUIPO_RAYO.Pasajes
DROP TABLE EQUIPO_RAYO.Facturas
DROP TABLE EQUIPO_RAYO.ItemFacturas